### ISSUE TITLE
Can't select end date in displacement time series window

### ISSUE THREAD

**Issue by falkamelung** [geodesymiami/insarmaps#53] opened 2021-10-03 21:43 UTC
Occasionaly I can't select the end date in time series window. It let's you select the start date and then it is doing things on its own.  Try this example:
```
https://insarmaps.miami.edu/start/19.4779/-155.5690/11.9600?flyToDatasetCenter=false&startDataset=CSK_SM_091_0000_20180916_XXXXXXXX&minScale=4&maxScale=-4
```
I can select the start date but then it does things without letting me select the end date as shown here:

https://user-images.githubusercontent.com/11162588/139192335-556a8d15-846a-402a-9905-26e472d58cc3.mov

Once you have fixed this please also verify this example. The display gets scrambled as shown in the video/

```
https://insarmaps.miami.edu/start/19.4779/-155.5690/11.9600?flyToDatasetCenter=false&startDataset=CSK_SM_091_0000_20180916_XXXXXXXX&minScale=4&maxScale=-4&pointLat=19.46509&pointLon=-155.57562&startDate=20210316&endDate=20210924
```

https://user-images.githubusercontent.com/11162588/135772418-07ff7837-b2c8-4bb5-8fe0-69e994602032.mov

**Comment by stackTom** [comment] 2022-07-30 16:20
This dataset seems to be deleted. Do you have another dataset I can use to reproduce this issue?

**Comment by falkamelung** [comment] 2022-07-30 16:26
It happens with almost every dataset. Do you think you have it fixed already? Then I should try many to see whether it still happens.

**Comment by stackTom** [comment] 2022-07-30 16:53
Possibly

**Comment by falkamelung** [comment] 2022-07-30 22:05
To what I see it works perfectly. This make a big difference!  I have to do some more testing though.

**Comment by falkamelung** [comment] 2022-07-30 22:30
For Sentinel-1 sensor it works fine (high-res and others), except a possible memory leak (more on that later). However for a different sensor (CSK) it does not work and the image get scrambled. Try this one and change the time period:

129.213.120.104/start/19.4880/-155.3734/9.1363?flyToDatasetCenter=false&startDataset=CSK_SM_091_0000_20180916_XXXXXXXX_N19330_N19578_W155725_W155430&pointLat=19.45323&pointLon=-155.55518&minScale=-3&maxScale=3&startDate=20190122&endDate=20200804

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/11162588/182002255-aaf88cd3-85ab-4ddf-804c-ddc263b83903.png">

**Comment by stackTom** [comment] 2022-07-30 22:44
I can't seem to reproduce it. I've seen this before as well but I can't consistently cause it. Do you know which conditions cause it? Maybe we just need to re upload those old datasets?

Also, what is the memory leak?

**Comment by falkamelung** [comment] 2022-07-30 22:52
That is weird. OK Will re-ingest later and look at it some more.

Regarding possible memory leak, please try this data set
http://129.213.120.104/start/19.4880/-155.3734/9.1363?flyToDatasetCenter=false&startDataset=S1_IW12_087_0527_0531_20141116_XXXXXXXX_N19391_N19549_W155679_W155506&minScale=-3&maxScale=3
and select a few times starting and end date. It gets very slow.

Then, after interupting using ESC it works fine again

**Comment by stackTom** [comment] 2022-07-31 01:28
I see what you mean. There is definitely a memory leak, good catch. I updated to the latest mapbox gl js. We were on version ~0.44 and the latest is 2.9.2, so we were very outdated. The new one doesn't suffer from the same slowdown when you recolor multiple times. Memory usage is also down significantly, so it appears they fixed whatever memory issue was there.

However, going from 0.44 to 2.9.2 is a huge change. I'm sure things will break (hopefully not) so keep an eye out for new weird bugs.

**Comment by stackTom** [comment] 2022-07-31 01:28
Maybe this also fixes the scrambling we see above. Let's keep using the site, if after a month or so the above issues aren't reproducible, let's close this issue as fixed.

**Closed** 2022-07-31 15:50 UTC
Labels: bug
